# Generated by Django 2.2.5 on 2019-09-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyLotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('round', models.PositiveIntegerField()),
                ('gamemethod', models.IntegerField()),
                ('gameamout', models.PositiveIntegerField()),
                ('gamemoney', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Winnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('num1', models.PositiveIntegerField()),
                ('num2', models.PositiveIntegerField()),
                ('num3', models.PositiveIntegerField()),
                ('num4', models.PositiveIntegerField()),
                ('num5', models.PositiveIntegerField()),
                ('num6', models.PositiveIntegerField()),
                ('bounusnum', models.PositiveIntegerField()),
                ('winneramount', models.CharField(max_length=10)),
                ('perprize', models.CharField(max_length=20)),
                ('winmethod', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GenLotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.PositiveIntegerField()),
                ('num2', models.PositiveIntegerField()),
                ('num3', models.PositiveIntegerField()),
                ('num4', models.PositiveIntegerField()),
                ('num5', models.PositiveIntegerField()),
                ('num6', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.MyLotto')),
            ],
        ),
    ]
